// Code generated by goctl. DO NOT EDIT.
// Source: imageServer.proto

package server

import (
	"context"

	"go-zero-container/app/image/cmd/rpc/internal/logic"
	"go-zero-container/app/image/cmd/rpc/internal/svc"
	"go-zero-container/app/image/cmd/rpc/pb/pb"
)

type ImageServerServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedImageServer
}

func NewImageServerServer(svcCtx *svc.ServiceContext) *ImageServerServer {
	return &ImageServerServer{
		svcCtx: svcCtx,
	}
}

func (s *ImageServerServer) GetMyImage(ctx context.Context, in *pb.GetMyImageReq) (*pb.GetMyImageResp, error) {
	l := logic.NewGetMyImageLogic(ctx, s.svcCtx)
	return l.GetMyImage(in)
}

func (s *ImageServerServer) GetUserImage(ctx context.Context, in *pb.GetUserImageReq) (*pb.GetUserImageResp, error) {
	l := logic.NewGetUserImageLogic(ctx, s.svcCtx)
	return l.GetUserImage(in)
}

func (s *ImageServerServer) GetAllImage(ctx context.Context, in *pb.GetAllImageReq) (*pb.GetAllImageResp, error) {
	l := logic.NewGetAllImageLogic(ctx, s.svcCtx)
	return l.GetAllImage(in)
}
