// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	image "go-zero-container/app/image/cmd/api/internal/handler/image"
	"go-zero-container/app/image/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/images/getAllImage",
				Handler: image.GetAllImageHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/images/getMyImage",
				Handler: image.GetMyImageHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/images/getUserImage",
				Handler: image.GetUserImageHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/image/v1"),
	)
}
