// Code generated by goctl. DO NOT EDIT.
package types

type CancelReq struct {
	Username string `json:"username"`
	Uuid     string `json:"uuid"`
}

type CancelResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	NickName     string `json:"nickname"`
	HeaderImg    string `json:"headerimg"`
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
}

type RegisterReq struct {
	Username    string `json:"username" example:"用户名"`
	Password    string `json:"password" example:"密码"`
	NickName    string `json:"nickname" example:"昵称"`
	HeaderImg   string `json:"headerimg,optional" example:"头像链接"`
	AuthorityId uint   `json:"authorityid" example:"int 角色id"`
	Phone       string `json:"phone" example:"电话号码"`
	Email       string `json:"email" example:"电子邮箱"`
}

type RegisterResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}
