// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.19.4
// source: imageServer.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImageRegistry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rid            int64  `protobuf:"varint,1,opt,name=Rid,proto3" json:"Rid,omitempty"`
	Kind           int32  `protobuf:"varint,2,opt,name=Kind,proto3" json:"Kind,omitempty"`
	UserId         uint64 `protobuf:"varint,3,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Name           string `protobuf:"bytes,4,opt,name=Name,proto3" json:"Name,omitempty"`
	Url            string `protobuf:"bytes,5,opt,name=Url,proto3" json:"Url,omitempty"`
	Authentication int32  `protobuf:"varint,6,opt,name=Authentication,proto3" json:"Authentication,omitempty"`
	Username       string `protobuf:"bytes,7,opt,name=Username,proto3" json:"Username,omitempty"`
	Password       string `protobuf:"bytes,8,opt,name=Password,proto3" json:"Password,omitempty"`
}

func (x *ImageRegistry) Reset() {
	*x = ImageRegistry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_imageServer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageRegistry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageRegistry) ProtoMessage() {}

func (x *ImageRegistry) ProtoReflect() protoreflect.Message {
	mi := &file_imageServer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageRegistry.ProtoReflect.Descriptor instead.
func (*ImageRegistry) Descriptor() ([]byte, []int) {
	return file_imageServer_proto_rawDescGZIP(), []int{0}
}

func (x *ImageRegistry) GetRid() int64 {
	if x != nil {
		return x.Rid
	}
	return 0
}

func (x *ImageRegistry) GetKind() int32 {
	if x != nil {
		return x.Kind
	}
	return 0
}

func (x *ImageRegistry) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ImageRegistry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ImageRegistry) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ImageRegistry) GetAuthentication() int32 {
	if x != nil {
		return x.Authentication
	}
	return 0
}

func (x *ImageRegistry) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ImageRegistry) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// 获取用户镜像时需携带参数
type GetUserImageReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
}

func (x *GetUserImageReq) Reset() {
	*x = GetUserImageReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_imageServer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserImageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserImageReq) ProtoMessage() {}

func (x *GetUserImageReq) ProtoReflect() protoreflect.Message {
	mi := &file_imageServer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserImageReq.ProtoReflect.Descriptor instead.
func (*GetUserImageReq) Descriptor() ([]byte, []int) {
	return file_imageServer_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserImageReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserImageResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImageRegistry []*ImageRegistry `protobuf:"bytes,1,rep,name=imageRegistry,proto3" json:"imageRegistry,omitempty"`
}

func (x *GetUserImageResp) Reset() {
	*x = GetUserImageResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_imageServer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserImageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserImageResp) ProtoMessage() {}

func (x *GetUserImageResp) ProtoReflect() protoreflect.Message {
	mi := &file_imageServer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserImageResp.ProtoReflect.Descriptor instead.
func (*GetUserImageResp) Descriptor() ([]byte, []int) {
	return file_imageServer_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserImageResp) GetImageRegistry() []*ImageRegistry {
	if x != nil {
		return x.ImageRegistry
	}
	return nil
}

// 获取个人镜像所返回参数
type GetMyImageReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetMyImageReq) Reset() {
	*x = GetMyImageReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_imageServer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMyImageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyImageReq) ProtoMessage() {}

func (x *GetMyImageReq) ProtoReflect() protoreflect.Message {
	mi := &file_imageServer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyImageReq.ProtoReflect.Descriptor instead.
func (*GetMyImageReq) Descriptor() ([]byte, []int) {
	return file_imageServer_proto_rawDescGZIP(), []int{3}
}

type GetMyImageResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImageRegistry []*ImageRegistry `protobuf:"bytes,1,rep,name=imageRegistry,proto3" json:"imageRegistry,omitempty"`
}

func (x *GetMyImageResp) Reset() {
	*x = GetMyImageResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_imageServer_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMyImageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyImageResp) ProtoMessage() {}

func (x *GetMyImageResp) ProtoReflect() protoreflect.Message {
	mi := &file_imageServer_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyImageResp.ProtoReflect.Descriptor instead.
func (*GetMyImageResp) Descriptor() ([]byte, []int) {
	return file_imageServer_proto_rawDescGZIP(), []int{4}
}

func (x *GetMyImageResp) GetImageRegistry() []*ImageRegistry {
	if x != nil {
		return x.ImageRegistry
	}
	return nil
}

// 获取所有镜像所返回参数
type GetAllImageReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAllImageReq) Reset() {
	*x = GetAllImageReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_imageServer_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllImageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllImageReq) ProtoMessage() {}

func (x *GetAllImageReq) ProtoReflect() protoreflect.Message {
	mi := &file_imageServer_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllImageReq.ProtoReflect.Descriptor instead.
func (*GetAllImageReq) Descriptor() ([]byte, []int) {
	return file_imageServer_proto_rawDescGZIP(), []int{5}
}

type GetAllImageResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImageRegistry []*ImageRegistry `protobuf:"bytes,1,rep,name=imageRegistry,proto3" json:"imageRegistry,omitempty"`
}

func (x *GetAllImageResp) Reset() {
	*x = GetAllImageResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_imageServer_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllImageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllImageResp) ProtoMessage() {}

func (x *GetAllImageResp) ProtoReflect() protoreflect.Message {
	mi := &file_imageServer_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllImageResp.ProtoReflect.Descriptor instead.
func (*GetAllImageResp) Descriptor() ([]byte, []int) {
	return file_imageServer_proto_rawDescGZIP(), []int{6}
}

func (x *GetAllImageResp) GetImageRegistry() []*ImageRegistry {
	if x != nil {
		return x.ImageRegistry
	}
	return nil
}

var File_imageServer_proto protoreflect.FileDescriptor

var file_imageServer_proto_rawDesc = []byte{
	0x0a, 0x11, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0xd3, 0x01, 0x0a, 0x0d, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x52, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x52, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4b,
	0x69, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x4b, 0x69, 0x6e, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x55,
	0x72, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55, 0x72, 0x6c, 0x12, 0x26, 0x0a,
	0x0e, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x29, 0x0a,
	0x0f, 0x67, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71,
	0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x4b, 0x0a, 0x10, 0x67, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x37, 0x0a, 0x0d,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x52, 0x0d, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x72, 0x79, 0x22, 0x0f, 0x0a, 0x0d, 0x67, 0x65, 0x74, 0x4d, 0x79, 0x49, 0x6d,
	0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x22, 0x49, 0x0a, 0x0e, 0x67, 0x65, 0x74, 0x4d, 0x79, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x37, 0x0a, 0x0d, 0x69, 0x6d, 0x61, 0x67,
	0x65, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x72, 0x79, 0x52, 0x0d, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72,
	0x79, 0x22, 0x10, 0x0a, 0x0e, 0x67, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x49, 0x6d, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x71, 0x22, 0x4a, 0x0a, 0x0f, 0x67, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x49, 0x6d, 0x61,
	0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x37, 0x0a, 0x0d, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x70, 0x62, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79,
	0x52, 0x0d, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x32,
	0xaf, 0x01, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x33, 0x0a, 0x0a, 0x67, 0x65, 0x74,
	0x4d, 0x79, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x67, 0x65, 0x74,
	0x4d, 0x79, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x70, 0x62, 0x2e,
	0x67, 0x65, 0x74, 0x4d, 0x79, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x39,
	0x0a, 0x0c, 0x67, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x13,
	0x2e, 0x70, 0x62, 0x2e, 0x67, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6d, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x67, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x36, 0x0a, 0x0b, 0x67, 0x65, 0x74,
	0x41, 0x6c, 0x6c, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x67, 0x65,
	0x74, 0x41, 0x6c, 0x6c, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x70,
	0x62, 0x2e, 0x67, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_imageServer_proto_rawDescOnce sync.Once
	file_imageServer_proto_rawDescData = file_imageServer_proto_rawDesc
)

func file_imageServer_proto_rawDescGZIP() []byte {
	file_imageServer_proto_rawDescOnce.Do(func() {
		file_imageServer_proto_rawDescData = protoimpl.X.CompressGZIP(file_imageServer_proto_rawDescData)
	})
	return file_imageServer_proto_rawDescData
}

var file_imageServer_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_imageServer_proto_goTypes = []interface{}{
	(*ImageRegistry)(nil),    // 0: pb.ImageRegistry
	(*GetUserImageReq)(nil),  // 1: pb.getUserImageReq
	(*GetUserImageResp)(nil), // 2: pb.getUserImageResp
	(*GetMyImageReq)(nil),    // 3: pb.getMyImageReq
	(*GetMyImageResp)(nil),   // 4: pb.getMyImageResp
	(*GetAllImageReq)(nil),   // 5: pb.getAllImageReq
	(*GetAllImageResp)(nil),  // 6: pb.getAllImageResp
}
var file_imageServer_proto_depIdxs = []int32{
	0, // 0: pb.getUserImageResp.imageRegistry:type_name -> pb.ImageRegistry
	0, // 1: pb.getMyImageResp.imageRegistry:type_name -> pb.ImageRegistry
	0, // 2: pb.getAllImageResp.imageRegistry:type_name -> pb.ImageRegistry
	3, // 3: pb.image.getMyImage:input_type -> pb.getMyImageReq
	1, // 4: pb.image.getUserImage:input_type -> pb.getUserImageReq
	5, // 5: pb.image.getAllImage:input_type -> pb.getAllImageReq
	4, // 6: pb.image.getMyImage:output_type -> pb.getMyImageResp
	2, // 7: pb.image.getUserImage:output_type -> pb.getUserImageResp
	6, // 8: pb.image.getAllImage:output_type -> pb.getAllImageResp
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_imageServer_proto_init() }
func file_imageServer_proto_init() {
	if File_imageServer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_imageServer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageRegistry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_imageServer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserImageReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_imageServer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserImageResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_imageServer_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMyImageReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_imageServer_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMyImageResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_imageServer_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllImageReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_imageServer_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllImageResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_imageServer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_imageServer_proto_goTypes,
		DependencyIndexes: file_imageServer_proto_depIdxs,
		MessageInfos:      file_imageServer_proto_msgTypes,
	}.Build()
	File_imageServer_proto = out.File
	file_imageServer_proto_rawDesc = nil
	file_imageServer_proto_goTypes = nil
	file_imageServer_proto_depIdxs = nil
}
